
_default:
	@just --list

fmt *args:
	npx @biomejs/biome format . {{ args }}

lint *args:
	npx @biomejs/biome lint . {{ args }}

diff *args:
	git diff {{ args }} ':!package-lock.json'

# use difftastic
difftastic *args:
	GIT_EXTERNAL_DIFF=difft git diff {{ args }} ':!package-lock.json'